# Generated by Django 3.0.8 on 2021-04-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0005_auto_20210424_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Complain Status',
                'verbose_name_plural': 'Complain Status',
            },
        ),
        migrations.CreateModel(
            name='TenantStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant Status',
                'verbose_name_plural': 'Tenant Status',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(max_length=255)),
                ('tenant_passport', models.CharField(max_length=255)),
                ('notes', models.TextField(max_length=8192)),
                ('tenant_id_file', models.FileField(blank=True, null=True, upload_to='tenant_id')),
                ('tenant_passport_file', models.FileField(blank=True, null=True, upload_to='tenant_passport')),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties', verbose_name='Property')),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyUnits', verbose_name='Property Unit')),
                ('tenant_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.TenantStatus', verbose_name='Tenant Status')),
            ],
            options={
                'verbose_name': 'Tenants',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='ComplainManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=8192)),
                ('complain_file', models.FileField(blank=True, null=True, upload_to='tenant_passport')),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('complain_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.ComplainStatus', verbose_name='Complain Status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant', verbose_name='Complain Management')),
            ],
        ),
    ]
