# Generated by Django 3.0.8 on 2021-04-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_auto_20210425_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='property',
        ),
    ]
