# Generated by Django 3.0.8 on 2021-04-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=75)),
                ('notes', models.TextField(max_length=8192)),
                ('number_of_units', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='property_logos/')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('contacts', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertType', verbose_name='Propert Type')),
            ],
        ),
    ]
