# Generated by Django 3.0.8 on 2021-04-24 08:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Amenities',
                'verbose_name_plural': 'Property Amenities',
            },
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Properties', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='properties',
            name='location_map',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PropertyUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_number', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('master_ensuite', models.BooleanField(default='NO')),
                ('notes', models.TextField(max_length=8192)),
                ('photos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='properties.ImageAlbum')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Units',
                'verbose_name_plural': 'Property Units',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=properties.models.get_upload_path)),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.ImageAlbum')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='property_ammenities',
            field=models.ManyToManyField(to='properties.PropertyAmenities', verbose_name='Propert Amenities'),
        ),
    ]
