# Generated by Django 3.0.8 on 2021-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210424_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunits',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyunits',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
