# Generated by Django 3.0.8 on 2021-04-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210424_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='propertyunits',
            name='photos',
        ),
        migrations.AddField(
            model_name='propertyunits',
            name='photos',
            field=models.ManyToManyField(related_name='images', to='properties.Image'),
        ),
    ]
