# Generated by Django 3.0.8 on 2021-04-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210424_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/unit_images/%Y/%m/%d/'),
        ),
    ]
