# Generated by Django 3.0.8 on 2021-04-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20210424_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunits',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
