# Generated by Django 3.0.8 on 2021-05-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyunits_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='properttype',
            name='notes',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='notes',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
    ]
