# Generated by Django 3.0.8 on 2021-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20210508_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenities',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
